# -*- coding: utf-8 -*-
"""Google_Cloud_Ai_Rescue_cordinator_copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0QU0N7XqTJtxF8xA3InLoR8mM93vfE1
"""

import os
import sys
import time
import atexit
import subprocess
from pathlib import Path

# Ensure matplotlib uses a writable temp cache directory
os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

BASE_DIR = Path(__file__).resolve().parent

try:
    from IPython.display import display
except ImportError:
    def display(*args, **kwargs):
        for arg in args:
            print(arg)

def kill_port(port: int = 8001):
    """Terminate any process listening on the specified port (macOS/Linux compatible)."""
    try:
        pids = subprocess.check_output(["lsof", "-ti", f":{port}"], text=True).strip().split()
        for pid in pids:
            if pid:
                os.kill(int(pid), 9)
    except Exception:
        pass

# Ensure any background servers on port 8001 are cleaned up on exit
atexit.register(kill_port)

# List the contents of the project directory (optional, for verification)
print("Contents of the cloned repository:")
for item in sorted(os.listdir(BASE_DIR)):
    print(f"  {item}")

readme_path = BASE_DIR / "README.md"
if readme_path.exists():
    with open(readme_path, 'r') as f:
        readme_content = f.read()
    print(readme_content)

# Install dependencies if needed (already managed in local venv)
# subprocess.run([sys.executable, "-m", "pip", "install", "-r", str(BASE_DIR / "requirements.txt")], check=False)

with open(BASE_DIR / 'scripts/smoke_test.py', 'r') as f:
    smoke_test_content = f.read()
print(smoke_test_content)

with open(BASE_DIR / 'app/config.py', 'r') as f:
    config_content = f.read()
print(config_content)

with open(BASE_DIR / 'app/database.py', 'r') as f:
    database_content = f.read()
print(database_content)

with open(BASE_DIR / 'app/main.py', 'r') as f:
    main_content = f.read()
print(main_content)

with open(BASE_DIR / 'app/api/routes.py', 'r') as f:
    routes_content = f.read()
print(routes_content)

with open(BASE_DIR / 'app/models.py', 'r') as f:
    models_content = f.read()
print("=== Models ===")
print(models_content)

with open(BASE_DIR / 'app/simulation/world_engine.py', 'r') as f:
    world_engine_content = f.read()
print("\n=== World Engine ===")
print(world_engine_content)

with open(BASE_DIR / 'app/agents/coordinator.py', 'r') as f:
    coordinator_content = f.read()
print("=== Coordinator ===")
print(coordinator_content)

with open(BASE_DIR / 'app/simulation/mission_sim.py', 'r') as f:
    mission_sim_content = f.read()
print("\n=== Mission Sim ===")
print(mission_sim_content)

with open(BASE_DIR / 'app/simulation/evaluator.py', 'r') as f:
    evaluator_content = f.read()
print("\n=== Evaluator ===")
print(evaluator_content)

# Start uvicorn in the background on port 8001
kill_port(8001)
print("Starting FastAPI Rescue Coordinator server on port 8001...")
server_process = subprocess.Popen(
    [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"],
    cwd=str(BASE_DIR)
)

# Let the server initialize
time.sleep(3)

# Check if the process started successfully
if server_process.poll() is None:
    print("FastAPI server started successfully in the background.")
else:
    print("Failed to start FastAPI server.")
    stdout, stderr = server_process.communicate()
    print("stdout:", stdout)
    print("stderr:", stderr)

# Run the smoke test to verify our simulation loop works
subprocess.run([sys.executable, str(BASE_DIR / "scripts" / "smoke_test.py")])

"""## Advanced Simulation: GIS, Skill Profiles, & Monte Carlo Rescue Missions

To make our AI Rescue Coordinator more realistic, let's build an analytical engine that models:

1. **GIS & Logistics**: Geographical locations for our volunteer responders and the incident scene, computing deployment response times using the **Haversine formula**.
2. **Volunteer Skill Profiles**: Skill vectors matching specific disaster demands.
3. **Markov Chain State Transitions**: Responders transitioning between statuses (e.g., `Healthy` → `Exhausted` → `Injured`) based on environmental stress, skill match, and travel fatigue.
4. **Monte Carlo Mission Simulation**: Simulating the rescue outcome hundreds of times to find success probability distributions.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

# --- 1. GIS & Haversine Distance Formula ---
def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)
    """
    # Convert decimal degrees to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])

    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.asin(math.sqrt(a))
    r = 6371 # Radius of earth in kilometers.
    return c * r

# --- 2. Define Incident Scene (GIS Location) ---
# Let's say a disaster occurred in Sector 7 Highway
incident_coords = (37.7749, -122.4194)  # San Francisco
print(f"Incident Coordinates (GIS): {incident_coords}")

# --- 3. Define Volunteer Skill Profiles & Spatial Coordinates ---
# Volunteers located at varying distances with distinct skills
volunteers = {
    "Alex": {"role": "Firefighter", "skills": {"Hazmat": 3, "Rescue": 2}, "lat": 37.7891, "lon": -122.4014}, # 2.1 km away
    "Sam": {"role": "Medic", "skills": {"Medical": 3, "Triage": 3}, "lat": 37.7564, "lon": -122.4431},     # 2.9 km away
    "Jordan": {"role": "Engineer", "skills": {"Structural": 3, "Hazmat": 1}, "lat": 37.7011, "lon": -122.4611}, # 8.9 km away
    "Casey": {"role": "Scout", "skills": {"Navigation": 3, "Rescue": 1}, "lat": 38.0124, "lon": -122.1245}     # 37.4 km away
}

# Build a logistics directory
volunteer_db = []
for name, info in volunteers.items():
    dist = haversine_distance(info["lat"], info["lon"], incident_coords[0], incident_coords[1])
    volunteer_db.append({
        "Name": name,
        "Role": info["role"],
        "Skills": info["skills"],
        "Distance (km)": round(dist, 2),
        "ETA (mins)": round(dist * 1.5, 1) # Assumes avg response speed of 40 km/h
    })

df_volunteers = pd.DataFrame(volunteer_db)
display(df_volunteers)

# --- 4. Markov Chain & Monte Carlo Mission Simulator ---
# Status States: 0: Healthy, 1: Exhausted, 2: Injured / Out of Action

def run_mission_monte_carlo(selected_volunteer, required_skill, num_epochs=1000, steps=6):
    """
    Run a Monte Carlo simulation using a state-transition Markov Chain.
    The probability of becoming exhausted/injured increases with distance (fatigue)
    and decreases with matching skills.
    """
    info = volunteers[selected_volunteer]
    dist = haversine_distance(info["lat"], info["lon"], incident_coords[0], incident_coords[1])
    skill_level = info["skills"].get(required_skill, 0)

    # Calculate customized transition matrix
    # Travel stress / fatigue factor scaling with distance
    fatigue_factor = min(0.3, dist / 100.0)
    # Skill factor decreases chance of mistakes/injury
    skill_protection = min(0.2, skill_level * 0.05)

    # Transition probability adjustments
    p_healthy_to_exhausted = max(0.05, 0.2 + fatigue_factor - skill_protection)
    p_exhausted_to_injured = max(0.02, 0.15 + fatigue_factor - skill_protection)

    # Markov Transition Matrix: [Healthy, Exhausted, Injured]
    transition_matrix = np.array([
        [1 - p_healthy_to_exhausted, p_healthy_to_exhausted, 0.0],
        [0.1, 0.9 - p_exhausted_to_injured, p_exhausted_to_injured],
        [0.0, 0.0, 1.0] # State 2 (Injured) is absorbing
    ])

    outcomes = []
    for _ in range(num_epochs):
        state = 0 # Start healthy
        for _ in range(steps):
            state = np.random.choice([0, 1, 2], p=transition_matrix[state])
        outcomes.append(state)

    # Summarize states at the end of the operation
    counts = pd.Series(outcomes).value_counts().reindex([0, 1, 2], fill_value=0)
    counts.index = ['Healthy', 'Exhausted', 'Injured/Out']
    return counts / num_epochs

# Run Monte Carlo simulation for Alex (Hazmat matching skill) vs Casey (Far, non-matching skill)
print("=== Monte Carlo Simulation Results ===")
for vol_name, req_s in [("Alex", "Hazmat"), ("Casey", "Hazmat")]:
    dist_prob = run_mission_monte_carlo(vol_name, req_s)
    print(f"\nVolunteer {vol_name} (Skill Level in '{req_s}': {volunteers[vol_name]['skills'].get(req_s, 0)}):")
    print(dist_prob)

# --- 5. Visualizing Monte Carlo Simulation Results ---
alex_results = run_mission_monte_carlo("Alex", "Hazmat")
casey_results = run_mission_monte_carlo("Casey", "Hazmat")

# Create visualization
x = np.arange(3)
width = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
rects1 = ax.bar(x - width/2, alex_results * 100, width, label='Alex (Close, High Skill)', color='#2ca02c')
rects2 = ax.bar(x + width/2, casey_results * 100, width, label='Casey (Far, No Skill)', color='#d62728')

ax.set_ylabel('Probability (%)')
ax.set_title('Mission Risk Analysis (Monte Carlo Simulation Outcomes)')
ax.set_xticks(x)
ax.set_xticklabels(['Healthy', 'Exhausted', 'Injured / Out'])
ax.legend()

plt.tight_layout()
plt.show()

coordinator_code = """
from typing import List
from app.models import Scenario, Survivor, Mission
import uuid
import math
import numpy as np

# Reference Incident Coordinate (San Francisco Center)
INCIDENT_LAT = 37.7749
INCIDENT_LON = -122.4194

# Simulated locations for default mock database survivors (lat, lon)
SURVIVOR_LOCATIONS = {
    "Alex": (37.7891, -122.4014),
    "Sam": (37.7564, -122.4431),
    "Jordan": (37.7011, -122.4611),
    "Casey": (38.0124, -122.1245),
    "Morgan": (37.7749, -122.4194),  # on-scene
    "Riley": (37.6879, -122.4014),
    "Quinn": (37.8044, -122.2711)
}

def haversine_distance(lat1, lon1, lat2, lon2):
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.asin(math.sqrt(a))
    return c * 6371

class Coordinator:
    def __init__(self):
        self.model = None  # Force local analytical engine

    async def assign_team(self, scenario: Scenario, survivors: List[Survivor]) -> Mission:
        scored_survivors = []
        required_skill = scenario.required_skills[0] if scenario.required_skills else "Rescue"

        for s in survivors:
            if s.status != "On-Call":
                continue

            # Resolve coordinates or default
            lat, lon = SURVIVOR_LOCATIONS.get(s.name, (37.7749, -122.4194))
            dist = haversine_distance(lat, lon, INCIDENT_LAT, INCIDENT_LON)

            # Monte Carlo Survival Estimation
            skill_level = s.skills.get(required_skill, 0)
            fatigue_factor = min(0.3, dist / 100.0)
            skill_protection = min(0.2, skill_level * 0.05)

            p_healthy_to_exhausted = max(0.05, 0.2 + fatigue_factor - skill_protection)
            p_exhausted_to_injured = max(0.02, 0.15 + fatigue_factor - skill_protection)

            transition_matrix = np.array([
                [1 - p_healthy_to_exhausted, p_healthy_to_exhausted, 0.0],
                [0.1, 0.9 - p_exhausted_to_injured, p_exhausted_to_injured],
                [0.0, 0.0, 1.0]
            ])

            # Simulating 500 epochs for computational efficiency on the API endpoint
            outcomes = []
            for _ in range(500):
                state = 0
                for _ in range(6):
                    state = np.random.choice([0, 1, 2], p=transition_matrix[state])
                outcomes.append(state)

            injury_rate = outcomes.count(2) / 500.0
            safety_score = 1.0 - injury_rate

            # Overall selection score (balance of safety and quick response)
            overall_score = safety_score * 0.7 + (1.0 / (dist + 1.0)) * 0.3

            scored_survivors.append({
                "id": s.id,
                "name": s.name,
                "score": overall_score,
                "dist": dist
            })

        # Sort by best score
        scored_survivors.sort(key=lambda x: x["score"], reverse=True)
        selected_ids = [s["id"] for s in scored_survivors[:3]]
        selected_names = [s["name"] for s in scored_survivors[:3]]

        print(f"Selected deployment team: {selected_names}")

        return Mission(
            id=str(uuid.uuid4()),
            scenario_id=scenario.id,
            assigned_team=selected_ids,
            log=[f"System Coordinator selected team based on GIS risk analysis: {', '.join(selected_names)}"]
        )
"""

with open(BASE_DIR / 'app/agents/coordinator.py', 'w') as f:
    f.write(coordinator_code)
print("Coordinator code has been successfully updated!")

updated_coordinator_code = """
from typing import List
from app.models import Scenario, Survivor, Mission
import uuid
import math
import numpy as np

# Reference Incident Coordinate (San Francisco Center)
INCIDENT_LAT = 37.7749
INCIDENT_LON = -122.4194

# Simulated locations for default mock database survivors (lat, lon)
SURVIVOR_LOCATIONS = {
    "Alex": (37.7891, -122.4014),
    "Sam": (37.7564, -122.4431),
    "Jordan": (37.7011, -122.4611),
    "Casey": (38.0124, -122.1245),
    "Morgan": (37.7749, -122.4194),  # on-scene
    "Riley": (37.6879, -122.4014),
    "Quinn": (37.8044, -122.2711)
}

def haversine_distance(lat1, lon1, lat2, lon2):
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.asin(math.sqrt(a))
    return c * 6371

class Coordinator:
    def __init__(self):
        self.model = None  # Force local analytical engine

    async def assign_team(self, scenario: Scenario, survivors: List[Survivor]) -> Mission:
        scored_survivors = []
        required_skill = scenario.required_skills[0] if scenario.required_skills else "Rescue"

        for s in survivors:
            if s.status != "On-Call":
                continue

            # Resolve coordinates or default
            lat, lon = SURVIVOR_LOCATIONS.get(s.name, (37.7749, -122.4194))
            dist = haversine_distance(lat, lon, INCIDENT_LAT, INCIDENT_LON)

            # Skill level
            skill_level = s.skills.get(required_skill, 0)

            # 1. Travel Fatigue & Skill Protection factors
            fatigue_factor = min(0.3, dist / 100.0)
            skill_protection = min(0.2, skill_level * 0.05)

            # 2. Probability Transitions
            p_healthy_to_exhausted = max(0.05, 0.2 + fatigue_factor - skill_protection)
            p_exhausted_to_injured = max(0.02, 0.15 + fatigue_factor - skill_protection)

            # 3. Estimating Survivability P_surv analytically
            p_surv = (1.0 - (p_healthy_to_exhausted * p_exhausted_to_injured)) ** 6

            # 4. Core Selection Utility score: U(d, S_k)
            overall_score = 0.7 * p_surv + 0.3 * (1.0 / (dist + 1.0))

            scored_survivors.append({
                "id": s.id,
                "name": s.name,
                "score": overall_score,
                "dist": dist
            })

        # Sort by best score
        scored_survivors.sort(key=lambda x: x["score"], reverse=True)
        selected_ids = [s["id"] for s in scored_survivors[:3]]
        selected_names = [s["name"] for s in scored_survivors[:3]]

        print(f"Selected deployment team: {selected_names}")

        return Mission(
            id=str(uuid.uuid4()),
            scenario_id=scenario.id,
            assigned_team=selected_ids,
            log=[f"System Coordinator selected team based on analytical utility score: {', '.join(selected_names)}"]
        )
"""

with open(BASE_DIR / 'app/agents/coordinator.py', 'w') as f:
    f.write(updated_coordinator_code)
print("Coordinator class updated to use the exact selection utility score formula!")

# Terminate old server, restart with updated code, and run smoke test
kill_port(8001)

print("Restarting FastAPI Rescue Coordinator...")
new_process = subprocess.Popen(
    [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"],
    cwd=str(BASE_DIR)
)

time.sleep(3)
if new_process.poll() is None:
    print("Server restarted successfully.")
    subprocess.run([sys.executable, str(BASE_DIR / "scripts" / "smoke_test.py")])
else:
    print("Uvicorn failed to start.")

# Terminate the previous server process running on port 8001
kill_port(8001)

# Start a new FastAPI server instance loading the updated Coordinator
print("Restarting FastAPI Rescue Coordinator server on port 8001...")
new_server_process = subprocess.Popen(
    [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"],
    cwd=str(BASE_DIR)
)

# Wait for the server to load resources and bind to port
time.sleep(3)
if new_server_process.poll() is None:
    print("FastAPI server restarted successfully.")
else:
    print("Failed to restart FastAPI server.")

# Run the smoke test to verify our new GIS/stochastic simulation logic
subprocess.run([sys.executable, str(BASE_DIR / "scripts" / "smoke_test.py")])

"""### Master Variables and Stochastic Parameters Configuration
Below is a master reference table detailing the parameters controlling the GIS logistics, Markov transitions, and Monte Carlo simulation. You can adjust any of these variables in the code block below to test different scenario behaviors and safety risk assessments.
"""

import pandas as pd

# Define the master parameters dictionary
config_variables = [
    {
        "Category": "GIS & Logistics",
        "Variable": "INCIDENT_LAT / INCIDENT_LON",
        "Default Value": "(37.7749, -122.4194)",
        "Description": "Reference epicenter coords (San Francisco). Manipulating this shifts the relative travel distance for all responders.",
        "Stochastic Potential": "Add Gaussian noise to simulate moving crisis locations (e.g., coordinates + np.random.normal(0, 0.01))."
    },
    {
        "Category": "GIS & Logistics",
        "Variable": "SURVIVOR_LOCATIONS",
        "Default Value": "Dictionary of static coords",
        "Description": "Physical location of each volunteer on dispatch.",
        "Stochastic Potential": "Randomize starting positions inside a bounding box to simulate real-world mobile shifts."
    },
    {
        "Category": "GIS & Logistics",
        "Variable": "Travel Speed Factor",
        "Default Value": "1.5 mins/km (40 km/h)",
        "Description": "Determines the ETA calculation.",
        "Stochastic Potential": "Incorporate traffic delays by multiplying by a random congestion multiplier (e.g., uniform(1.0, 2.5))."
    },
    {
        "Category": "Markov Transitions",
        "Variable": "p_healthy_to_exhausted",
        "Default Value": "max(0.05, 0.2 + fatigue - skill_prot)",
        "Description": "Baseline probability of a healthy responder becoming fatigued.",
        "Stochastic Potential": "Can scale dynamically based on the severity rating of the active disaster scenario."
    },
    {
        "Category": "Markov Transitions",
        "Variable": "p_exhausted_to_injured",
        "Default Value": "max(0.02, 0.15 + fatigue - skill_prot)",
        "Description": "Baseline probability of an exhausted responder suffering an operational injury.",
        "Stochastic Potential": "Add random environmental spikes (e.g., sudden weather changes or toxic flares)."
    },
    {
        "Category": "Monte Carlo",
        "Variable": "num_epochs",
        "Default Value": "500 (API) / 1000 (Local)",
        "Description": "Number of operational trials simulated to resolve output probability profiles.",
        "Stochastic Potential": "N/A (Represents confidence level; higher epochs reduce outcome variance)."
    }
]

# Create and display the DataFrame
df_config = pd.DataFrame(config_variables)
pd.set_option('display.max_colwidth', None)
display(df_config)

"""## Digital Twin & Synthetic Dataset Generator for ML Training

To build a machine learning model (e.g., predicting team survivability or directly learning our utility decision surface), we need a scalable pipeline to generate high-fidelity synthetic training data.

This Digital Twin engine generates realistic disaster scenarios of varying severity and pairs them with randomly distributed volunteer teams, logging logistics features and calculating our stochastic survivability label.
"""

import numpy as np
import pandas as pd

class DigitalTwinEngine:
    def __init__(self, incident_coords=(37.7749, -122.4194)):
        self.incident_lat, self.incident_lon = incident_coords

    def generate_synthetic_dataset(self, num_samples=5000):
        data_records = []

        for _ in range(num_samples):
            # 1. Randomize Scenario Metrics
            scenario_severity = np.random.randint(1, 6)  # 1 to 5 scale

            # 2. Randomize Volunteer GIS & Profile
            # Randomize distance from epicenter between 0.5 km to 50 km
            distance_km = np.random.exponential(scale=15.0)  # dense close by, sparse far away
            distance_km = np.clip(distance_km, 0.5, 75.0)

            # Volunteer skill profile matching target required skill (0 to 3 rating)
            skill_level = np.random.choice([0, 1, 2, 3], p=[0.25, 0.35, 0.30, 0.10])

            # 3. Apply the Stochastic Transition Engine Formulas
            fatigue_factor = min(0.3, distance_km / 100.0)
            skill_protection = min(0.2, skill_level * 0.05)

            p_healthy_to_exhausted = max(0.05, 0.2 + fatigue_factor - skill_protection)
            p_exhausted_to_injured = max(0.02, 0.15 + fatigue_factor - skill_protection)

            # Analytical survivability mapping
            p_surv = (1.0 - (p_healthy_to_exhausted * p_exhausted_to_injured)) ** 6

            # Core decision score U(d, S_k)
            selection_utility = 0.7 * p_surv + 0.3 * (1.0 / (distance_km + 1.0))

            # Add Gaussian noise to simulation outputs to represent physical real-world environment noise
            simulated_noise = np.random.normal(0, 0.02)
            noisy_surv = np.clip(p_surv + simulated_noise, 0.0, 1.0)

            # Build dataset row
            data_records.append({
                "scenario_severity": scenario_severity,
                "distance_km": round(distance_km, 4),
                "skill_level": skill_level,
                "fatigue_factor": round(fatigue_factor, 4),
                "p_healthy_to_exhausted": round(p_healthy_to_exhausted, 4),
                "p_exhausted_to_injured": round(p_exhausted_to_injured, 4),
                "target_surv_probability": round(p_surv, 4),
                "noisy_surv_empirical": round(noisy_surv, 4),
                "selection_utility": round(selection_utility, 4)
            })

        return pd.DataFrame(data_records)

# Instantiate the Digital Twin engine
twin_engine = DigitalTwinEngine()
df_twin_dataset = twin_engine.generate_synthetic_dataset(num_samples=2500)

# Display the top rows of the generated Digital Twin dataset
display(df_twin_dataset.head(10))

"""### Dataset Analysis & Training Metrics
We will now run a quick summary to see if the dataset covers distinct operational profiles, which will ensure that any ML classifier or regression model trained on this data is well-generalized.
"""

# Print feature correlation with survivability and selection utility
correlation_matrix = df_twin_dataset[["scenario_severity", "distance_km", "skill_level", "target_surv_probability", "selection_utility"]].corr()
print("=== Feature Correlations with Target Variables ===")
display(correlation_matrix)

"""## Machine Learning Training on the Digital Twin Dataset

Using the synthetic dataset generated by our Digital Twin engine, we will train a model to map telemetry metrics (`distance_km`, `skill_level`) to target survivability. This demonstrates the loop of using a physics/logistics simulation engine as a training ground for neural networks or ensemble models.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt

# 1. Prepare Features and Targets
# We will use distance and skill level to predict the simulated survivability
X = df_twin_dataset[['distance_km', 'skill_level']]
y = df_twin_dataset['target_surv_probability']

# Split into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Train the Machine Learning Model
ml_model = RandomForestRegressor(n_estimators=100, random_state=42)
ml_model.fit(X_train, y_train)

# 3. Predict & Collect Performance Metrics
y_pred = ml_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("=== Machine Learning Model Metrics ===")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"R-squared (R²) Score:      {r2:.4f}")

# 4. Plot Predicted vs. Actual Survivability
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.4, color='#1f77b4')
plt.plot([0, 1], [0, 1], 'r--', lw=2, label='Perfect Mirror Line')
plt.title('Digital Twin: Actual vs. ML-Predicted Survivability')
plt.xlabel('Simulated Target Survivability')
plt.ylabel('ML-Predicted Survivability')
plt.legend()
plt.grid(True)
plt.show()

"""## Machine Learning Training on the Digital Twin Dataset

Using the synthetic dataset generated by our Digital Twin engine, we will train a model to map telemetry metrics (`distance_km`, `skill_level`) to target survivability. This demonstrates the loop of using a physics/logistics simulation engine as a training ground for neural networks or ensemble models.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt

# 1. Prepare Features and Targets
# We will use distance and skill level to predict the simulated survivability
X = df_twin_dataset[['distance_km', 'skill_level']]
y = df_twin_dataset['target_surv_probability']

# Split into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Train the Machine Learning Model
ml_model = RandomForestRegressor(n_estimators=100, random_state=42)
ml_model.fit(X_train, y_train)

# 3. Predict & Collect Performance Metrics
y_pred = ml_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("=== Machine Learning Model Metrics ===")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"R-squared (R²) Score:      {r2:.4f}")

# 4. Plot Predicted vs. Actual Survivability
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.4, color='#1f77b4')
plt.plot([0, 1], [0, 1], 'r--', lw=2, label='Perfect Mirror Line')
plt.title('Digital Twin: Actual vs. ML-Predicted Survivability')
plt.xlabel('Simulated Target Survivability')
plt.ylabel('ML-Predicted Survivability')
plt.legend()
plt.grid(True)
plt.show()

"""### Dynamic Weather Simulation Engine

We will define a set of weather configurations. Each weather condition has:
* `speed_multiplier`: Scales travel duration (e.g., `0.5` means traveling takes twice as long).
* `stress_multiplier`: Multiplies the transitions to higher fatigue or injury states.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Define Weather Configurations
WEATHER_PROFILES = {
    "Clear": {"speed_multiplier": 1.0, "stress_multiplier": 1.0},
    "Rain": {"speed_multiplier": 0.8, "stress_multiplier": 1.2},
    "Fog": {"speed_multiplier": 0.6, "stress_multiplier": 1.3},
    "Snow": {"speed_multiplier": 0.5, "stress_multiplier": 1.5},
    "Storm": {"speed_multiplier": 0.4, "stress_multiplier": 1.8}
}

# 2. Weather-Aware Simulation Core
def run_weather_aware_sim(selected_volunteer, required_skill, weather_name, num_epochs=1000, steps=6):
    info = volunteers[selected_volunteer]
    dist = haversine_distance(info["lat"], info["lon"], incident_coords[0], incident_coords[1])
    skill_level = info["skills"].get(required_skill, 0)

    # Get weather effects
    weather = WEATHER_PROFILES.get(weather_name, WEATHER_PROFILES["Clear"])
    speed_mult = weather["speed_multiplier"]
    stress_mult = weather["stress_multiplier"]

    # Calculate travel times with weather delays
    base_eta = dist * 1.5 # 1.5 mins/km
    weather_eta = base_eta / speed_mult

    # Transition probability scaling with travel stress & weather conditions
    fatigue_factor = min(0.3, dist / 100.0)
    skill_protection = min(0.2, skill_level * 0.05)

    p_healthy_to_exhausted = max(0.05, (0.2 + fatigue_factor - skill_protection) * stress_mult)
    p_exhausted_to_injured = max(0.02, (0.15 + fatigue_factor - skill_protection) * stress_mult)

    # Ensure probability constraints (bounds [0, 1])
    p_healthy_to_exhausted = min(0.95, p_healthy_to_exhausted)
    p_exhausted_to_injured = min(0.95, p_exhausted_to_injured)

    # Markov Matrix with weather-induced risk changes
    transition_matrix = np.array([
        [1.0 - p_healthy_to_exhausted, p_healthy_to_exhausted, 0.0],
        [0.1, 0.9 - p_exhausted_to_injured, p_exhausted_to_injured],
        [0.0, 0.0, 1.0]
    ])

    outcomes = []
    for _ in range(num_epochs):
        state = 0
        for _ in range(steps):
            state = np.random.choice([0, 1, 2], p=transition_matrix[state])
        outcomes.append(state)

    counts = pd.Series(outcomes).value_counts().reindex([0, 1, 2], fill_value=0)
    counts.index = ['Healthy', 'Exhausted', 'Injured/Out']
    probabilities = counts / num_epochs

    return {
        "eta_mins": round(weather_eta, 1),
        "probabilities": probabilities
    }

"""### Evaluating the Impact of Severe Storm vs. Clear Weather

Let's run a comparative simulation for **Alex** under both `Clear` and `Storm` scenarios to see how response ETAs and volunteer physical health deteriorate under heavy storm hazards.
"""

clear_sim = run_weather_aware_sim("Alex", "Hazmat", "Clear")
storm_sim = run_weather_aware_sim("Alex", "Hazmat", "Storm")

print(f"=== Logistics Summary for Alex (Distance: {df_volunteers.loc[0, 'Distance (km)']} km) ===")
print(f"Clear Weather Response ETA: {clear_sim['eta_mins']} minutes")
print(f"Stormy Weather Response ETA: {storm_sim['eta_mins']} minutes ({(storm_sim['eta_mins']/clear_sim['eta_mins']):.1f}x delay)\n")

# Visual comparison of safety risks
x = np.arange(3)
width = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
rects1 = ax.bar(x - width/2, clear_sim['probabilities'] * 100, width, label='Clear Weather', color='#34a853')
rects2 = ax.bar(x + width/2, storm_sim['probabilities'] * 100, width, label='Storm Weather', color='#ea4335')

ax.set_ylabel('Probability (%)')
ax.set_title('Weather Impact on Volunteer Injury & Fatigue Rates')
ax.set_xticks(x)
ax.set_xticklabels(['Healthy', 'Exhausted', 'Injured / Out'])
ax.legend()

plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""### Upgrading the Digital Twin & Machine Learning Model with Weather Severity

We will now incorporate **weather severity** into our ML training dataset. We will map our weather profiles to a numerical index (e.g., Clear=1, Storm=5) and generate a new dataset where the target survivability is calculated incorporating weather stress. Then, we will train an upgraded Random Forest Regressor to capture this multi-variable physical boundary.
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt

# Map weather profiles to a numerical intensity scale [1, 5]
WEATHER_SEVERITY_MAP = {
    "Clear": 1,
    "Rain": 2,
    "Fog": 3,
    "Snow": 4,
    "Storm": 5
}

class WeatherAwareDigitalTwinEngine:
    def __init__(self):
        pass

    def generate_weather_dataset(self, num_samples=3000):
        data_records = []
        weather_keys = list(WEATHER_PROFILES.keys())

        for _ in range(num_samples):
            # Randomize variables
            distance_km = np.random.exponential(scale=15.0)
            distance_km = np.clip(distance_km, 0.5, 75.0)

            skill_level = np.random.choice([0, 1, 2, 3], p=[0.25, 0.35, 0.30, 0.10])

            # Randomly select weather
            weather_name = np.random.choice(weather_keys)
            weather_intensity = WEATHER_SEVERITY_MAP[weather_name]
            stress_mult = WEATHER_PROFILES[weather_name]["stress_multiplier"]

            # Apply stochastic transition formula with weather stress
            fatigue_factor = min(0.3, distance_km / 100.0)
            skill_protection = min(0.2, skill_level * 0.05)

            p_healthy_to_exhausted = min(0.95, max(0.05, (0.2 + fatigue_factor - skill_protection) * stress_mult))
            p_exhausted_to_injured = min(0.95, max(0.02, (0.15 + fatigue_factor - skill_protection) * stress_mult))

            # Calculate analytical survivability
            p_surv = (1.0 - (p_healthy_to_exhausted * p_exhausted_to_injured)) ** 6

            data_records.append({
                "distance_km": round(distance_km, 4),
                "skill_level": skill_level,
                "weather_severity": weather_intensity,
                "target_surv_probability": round(p_surv, 4)
            })

        return pd.DataFrame(data_records)

# 1. Generate upgraded dataset
twin_weather_engine = WeatherAwareDigitalTwinEngine()
df_weather_twin = twin_weather_engine.generate_weather_dataset(num_samples=3000)

# 2. Split features and target
X_w = df_weather_twin[['distance_km', 'skill_level', 'weather_severity']]
y_w = df_weather_twin['target_surv_probability']

X_train_w, X_test_w, y_train_w, y_test_w = train_test_split(X_w, y_w, test_size=0.2, random_state=42)

# 3. Train the updated ML model
weather_ml_model = RandomForestRegressor(n_estimators=100, random_state=42)
weather_ml_model.fit(X_train_w, y_train_w)

# 4. Predict & Evaluate
y_pred_w = weather_ml_model.predict(X_test_w)

print("=== Upgraded ML Model Metrics (with Weather Severity) ===")
print(f"Mean Absolute Error (MAE): {mean_absolute_error(y_test_w, y_pred_w):.4f}")
print(f"R-squared (R²) Score:      {r2_score(y_test_w, y_pred_w):.4f}\n")

# 5. Feature Importance Analysis
importances = weather_ml_model.feature_importances_
for feature, importance in zip(X_w.columns, importances):
    print(f"Feature '{feature}': {importance:.4f} importance score")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Create a sliding test envelope for distance (from 0.5 to 75 km) vs. Survivability
sliding_distances = np.linspace(0.5, 75.0, 300)

# We will test two scenarios:
# Scenario A: Skill Level 3 under Clear Weather (Severity 1)
# Scenario B: Skill Level 1 under Storm Weather (Severity 5)

ground_truth_clean = []
ml_predicted_clean = []
ground_truth_storm = []
ml_predicted_storm = []

for d in sliding_distances:
    # --- Scenario A Ground Truth ---
    fatigue_a = min(0.3, d / 100.0)
    prot_a = min(0.2, 3 * 0.05) # skill 3
    p_h_to_e_a = min(0.95, max(0.05, (0.2 + fatigue_a - prot_a) * 1.0))
    p_e_to_i_a = min(0.95, max(0.02, (0.15 + fatigue_a - prot_a) * 1.0))
    p_surv_a = (1.0 - (p_h_to_e_a * p_e_to_i_a)) ** 6
    ground_truth_clean.append(p_surv_a)

    # --- Scenario A ML Prediction (Using DataFrame with feature names to suppress warnings) ---
    df_query_a = pd.DataFrame([[d, 3, 1]], columns=['distance_km', 'skill_level', 'weather_severity'])
    ml_pred_a = weather_ml_model.predict(df_query_a)[0]
    ml_predicted_clean.append(ml_pred_a)

    # --- Scenario B Ground Truth ---
    fatigue_b = min(0.3, d / 100.0)
    prot_b = min(0.2, 1 * 0.05) # skill 1
    p_h_to_e_b = min(0.95, max(0.05, (0.2 + fatigue_b - prot_b) * 1.8))
    p_e_to_i_b = min(0.95, max(0.02, (0.15 + fatigue_b - prot_b) * 1.8))
    p_surv_b = (1.0 - (p_h_to_e_b * p_e_to_i_b)) ** 6
    ground_truth_storm.append(p_surv_b)

    # --- Scenario B ML Prediction (Using DataFrame with feature names to suppress warnings) ---
    df_query_b = pd.DataFrame([[d, 1, 5]], columns=['distance_km', 'skill_level', 'weather_severity'])
    ml_pred_b = weather_ml_model.predict(df_query_b)[0]
    ml_predicted_storm.append(ml_pred_b)

# 2. Plot Comparisons
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# Plot 1: Clear Weather, High Skill (Ground Truth vs ML)
axes[0].plot(sliding_distances, ground_truth_clean, 'g-', label='Markov Ground-Truth', linewidth=2.5)
axes[0].plot(sliding_distances, ml_predicted_clean, 'o', color='darkgreen', alpha=0.5, markersize=4, label='ML Regressor Prediction')
axes[0].set_title('Clear Weather (Skill 3)\nMarkov Ground-Truth vs ML')
axes[0].set_xlabel('Distance (km)')
axes[0].set_ylabel('Survival Probability')
axes[0].grid(True, linestyle='--', alpha=0.5)
axes[0].legend()

# Plot 2: Stormy Weather, Low Skill (Ground Truth vs ML)
axes[1].plot(sliding_distances, ground_truth_storm, 'r-', label='Markov Ground-Truth', linewidth=2.5)
axes[1].plot(sliding_distances, ml_predicted_storm, 'o', color='darkred', alpha=0.5, markersize=4, label='ML Regressor Prediction')
axes[1].set_title('Stormy Weather (Skill 1)\nMarkov Ground-Truth vs ML')
axes[1].set_xlabel('Distance (km)')
axes[1].set_ylabel('Survival Probability')
axes[1].grid(True, linestyle='--', alpha=0.5)
axes[1].legend()

# Plot 3: Dynamic Weather Severity Impact on ML Predictions
severities = np.linspace(1, 5, 100)
severity_queries = pd.DataFrame([
    [25.0, 2, s] for s in severities
], columns=['distance_km', 'skill_level', 'weather_severity'])
severity_predictions = weather_ml_model.predict(severity_queries)

axes[2].plot(severities, severity_predictions, color='#4285f4', linewidth=3, label='ML Predicted curve')
axes[2].set_xticks([1, 2, 3, 4, 5])
axes[2].set_xticklabels(['Clear (1)', 'Rain (2)', 'Fog (3)', 'Snow (4)', 'Storm (5)'])
axes[2].set_title('Weather Impact on ML Survival Predictions\n(At 25 km Distance, Skill Level 2)')
axes[2].set_xlabel('Weather Severity')
axes[2].set_ylabel('Predicted Survival Probability')
axes[2].grid(True, linestyle='--', alpha=0.5)
axes[2].legend()

plt.tight_layout()
plt.show()

# Plot Feature Importance
plt.figure(figsize=(8, 4))
plt.barh(X_w.columns, importances, color=['#4285f4', '#34a853', '#fabc05'])
plt.title('Random Forest Feature Importance (Weather-Aware Model)')
plt.xlabel('Importance Score')
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""### 3D Spatial and Climatic Risk Topography

To visualize how travel distance, volunteer skill level, and weather severity collectively influence survival probability, we will render a 3D scatter plot. This projection shows the boundary envelope where missions shift from highly successful (green) to catastrophic failures (red).
"""

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Scatter plotting features:
# X-axis: Distance (km)
# Y-axis: Weather Severity (1-5)
# Z-axis: Predicted/Actual Survivability Probability
# Color: Map the target survivability value (using 'RdYlGn' where red is low and green is high survivability)

scatter = ax.scatter(
    df_weather_twin['distance_km'],
    df_weather_twin['weather_severity'],
    df_weather_twin['target_surv_probability'],
    c=df_weather_twin['target_surv_probability'],
    cmap='RdYlGn',
    alpha=0.6,
    edgecolors='none',
    s=15
)

# Customize axis labels and titles
ax.set_title('3D Telemetry Envelope: Survivability vs. Distance & Weather Severity', fontsize=14, pad=20)
ax.set_xlabel('Travel Distance (km)', fontsize=11, labelpad=10)
ax.set_ylabel('Weather Severity (Index 1-5)', fontsize=11, labelpad=10)
ax.set_zlabel('Survivability Probability', fontsize=11, labelpad=10)

# Add a color bar mapping the hazard spectrum
cbar = fig.colorbar(scatter, ax=ax, shrink=0.5, aspect=10)
cbar.set_label('Survival Rate', rotation=270, labelpad=15)

# Adjust initial viewing angle for optimal perspective
ax.view_init(elev=25, azim=45)

plt.tight_layout()
plt.show()

r"""# Companion Guide: Mathematics, Data Science, and Machine Learning of the AI Rescue Coordinator

This guide serves as an educational companion to the AI Rescue Coordinator project. Below we break down the rigorous mathematics, probabilistic theory, and machine learning algorithms utilized across the simulator.

---

## Table of Contents
1. [Trigonometry & GIS: The Haversine Distance Formula](#1-trigonometry--gis-the-haversine-distance-formula)
2. [Probability & Stochastic Processes: Markov Chain Transition Modeling](#2-probability--stochastic-processes-markov-chain-transition-modeling)
3. [Multi-Attribute Utility Theory (MAUT): Optimal Team Selection](#3-multi-attribute-utility-theory-maut-optimal-team-selection)
4. [Simulation Methods: Monte Carlo Risk Estimation](#4-simulation-methods-monte-carlo-risk-estimation)
5. [Machine Learning: Non-Linear Regression & Random Forests](#5-machine-learning-non-linear-regression--random-forests)

---

## 1. Trigonometry & GIS: The Haversine Distance Formula

In typical planar geometry, we use Euclidean distance ($d = \sqrt{\Delta x^2 + \Delta y^2}$). However, the Earth is an oblate spheroid, meaning flat calculations introduce severe distortions over long distances. To calculate the shortest spherical distance between a responder and a crisis scene, we must use **spherical trigonometry**.

### The Mathematical Derivation
Let $(\phi_1, \lambda_1)$ and $(\phi_2, \lambda_2)$ be the latitude and longitude of two points in radians.

The central angle $\theta$ between them is defined by the spherical law of cosines. For numerical stability on computers (especially when calculating very small distances), we employ the **Haversine formula**, which avoids rounding errors caused by small cosine values:

$$\text{hav}(\theta) = \text{hav}(\phi_2 - \phi_1) + \cos(\phi_1)\cos(\phi_2)\text{hav}(\lambda_2 - \lambda_1)$$

Where the haversine function is:
$$\text{hav}(x) = \sin^2\left(\frac{x}{2}\right)$$

Substituting this definition in, we compute the term $a$:
$$a = \sin^2\left(\frac{\Delta \phi}{2}\right) + \cos(\phi_1)\cos(\phi_2)\sin^2\left(\frac{\Delta \lambda}{2}\right)$$

We then solve for the central angle $c$ using the arctangent function for robustness:
$$c = 2 \cdot \text{arcsin}(\sqrt{a})$$

Finally, the arc length distance $d$ along the sphere with radius $R \approx 6371 \text{ km}$ is:
$$d = R \cdot c$$

---

## 2. Probability & Stochastic Processes: Markov Chain Transition Modeling

A volunteer's physical safety during a deployment is modeled using a **Discrete-Time Markov Chain (DTMC)**. A Markov chain represents a system of states where the probability of transitioning to the next state depends *solely* on the current state (called the **Markov Property**):

$$P(X_{t+1} = x_{t+1} \mid X_t = x_t, X_{t-1} = x_{t-1}, \dots, X_0 = x_0) = P(X_{t+1} = x_{t+1} \mid X_t = x_t)$$

### State Space & Transition Matrix
Our model utilizes three discrete states:
1. **State 0 (Healthy)**
2. **State 1 (Exhausted)**
3. **State 2 (Injured / Out of Action)**

The probability of transitioning between states is written as a stochastic transition matrix $P$:

$$P = \begin{pmatrix}
P_{00} & P_{01} & P_{02} \\
P_{10} & P_{11} & P_{12} \\
P_{20} & P_{21} & P_{22}
\end{pmatrix} = \begin{pmatrix}
1 - p_{\text{exhaust}} & p_{\text{exhaust}} & 0.0 \\
0.1 & 0.9 - p_{\text{injury}} & p_{\text{injury}} \\
0.0 & 0.0 & 1.0
\end{pmatrix}$$

* **Absorbing State**: State 2 is an *absorbing state* ($P_{22} = 1.0$). Once a volunteer becomes injured, they cannot recover or transition back to healthy during the operational timeline of the active mission.
* **Environmental Constraints**: The transition rates $p_{\text{exhaust}}$ and $p_{\text{injury}}$ are calculated dynamically based on GIS distance ($d$) and matching skills ($S_k$):
  $$p_{\text{exhaust}} = \max(0.05, 0.2 + \text{fatigue}(d) - \text{protection}(S_k)) \cdot \text{WeatherStress}$$

---

## 3. Multi-Attribute Utility Theory (MAUT): Optimal Team Selection

When a crisis strikes, the coordinator must select the optimal responders. We cannot optimize solely for the closest responder (who might have zero matching skills and a high risk of injury) or solely for the most skilled responder (who might be too far away to arrive in time). We resolve this using **Multi-Attribute Utility Theory (MAUT)**.

We construct an objective utility function $U(d, S_k)$ to map multiple competing objectives into a single real-valued scalar $[0, 1]$:

$$U(d, S_k) = w_1 \cdot P_{\text{surv}}(d, S_k) + w_2 \cdot T(d)$$

Where:
* $P_{\text{surv}}$ is the analytical safe-mission survival rate.
* $T(d) = \frac{1}{d + 1}$ is a bounded, non-linear function representing arrival efficiency (as $d \to 0$, $T \to 1$; as $d \to \infty$, $T \to 0$).
* $w_1 = 0.7$ and $w_2 = 0.3$ represent the weight vector, formalizing our operational prioritization of safety over speed.

---

## 4. Simulation Methods: Monte Carlo Risk Estimation

While simple Markov transitions have direct algebraic solutions, real-world systems are filled with complex branching paths, weather dynamics, and nested conditions. To estimate risks empirically under any arbitrary model, we use **Monte Carlo simulations**.

### The Law of Large Numbers (LLN)
By simulating $N$ independent runs (epochs) of the Markov Chain, we record the final outcomes $x_1, x_2, \dots, x_N$. The Law of Large Numbers guarantees that the empirical average of these trials converges to the true expected mathematical probability as $N$ grows large:

$$\lim_{N \to \infty} \frac{1}{N} \sum_{i=1}^N \mathbb{I}(X^{(i)} = \text{State}) = P(X = \text{State})$$

This technique allows the coordinator to evaluate non-linear risk outcomes (such as dynamic storms or shifting coordinate hazards) without needing complex differential equation solvers.

---

## 5. Machine Learning: Non-Linear Regression & Random Forests

Once our Digital Twin simulates thousands of missions, we obtain a dense dataset containing complex physical and logistical interactions. We train a **Random Forest Regressor** on this data.

### Decision Trees & Ensemble Learning
A single decision tree splits data recursively to minimize mean squared error (MSE) variance in each node. However, individual trees suffer from high variance and overfit easily.

**Random Forest** corrects this through two primary mechanisms:
1. **Bootstrap Aggregating (Bagging)**: Training $B$ individual trees on random bootstrap subsets of the dataset.
2. **Feature Randomization**: At each split, only a random subset of features is evaluated. This decorrelates the trees.

The final regressor prediction is the average of all $B$ decision trees:

$$\hat{y} = \frac{1}{B} \sum_{b=1}^{B} T_b(x)$$

### Performance Evaluation
* **Mean Absolute Error (MAE)**: Measures average magnitude of prediction errors:
  $$\text{MAE} = \frac{1}{n} \sum_{i=1}^n |y_i - \hat{y}_i|$$
* **R-squared ($R^2$) Coefficient of Determination**: Represents the proportion of variance in the target variable explained by our features:
  $$R^2 = 1 - \frac{\sum (y_i - \hat{y}_i)^2}{\sum (y_i - \bar{y})^2}$$

An $R^2$ of `1.0000` indicates that our Random Forest has perfectly learned the non-linear physics of the simulator!
"""